"""Initial migration.

Revision ID: 3b2e8ccbf9eb
Revises: 
Create Date: 2024-09-22 01:29:21.325437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b2e8ccbf9eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nba_players')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nba_players',
    sa.Column('id_table', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('playerName', sa.VARCHAR(length=80), nullable=False),
    sa.Column('position', sa.VARCHAR(length=80), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=False),
    sa.Column('games', sa.INTEGER(), nullable=True),
    sa.Column('gamesStarted', sa.INTEGER(), nullable=True),
    sa.Column('minutesPg', sa.INTEGER(), nullable=False),
    sa.Column('fieldGoals', sa.INTEGER(), nullable=True),
    sa.Column('fieldAttempts', sa.INTEGER(), nullable=True),
    sa.Column('fieldPercent', sa.FLOAT(), nullable=True),
    sa.Column('threeFg', sa.INTEGER(), nullable=True),
    sa.Column('threeAttempts', sa.INTEGER(), nullable=True),
    sa.Column('threePercent', sa.FLOAT(), nullable=True),
    sa.Column('twoFg', sa.INTEGER(), nullable=True),
    sa.Column('twoAttempts', sa.INTEGER(), nullable=True),
    sa.Column('twoPercent', sa.FLOAT(), nullable=True),
    sa.Column('effectFgPercent', sa.FLOAT(), nullable=True),
    sa.Column('ft', sa.INTEGER(), nullable=True),
    sa.Column('ftAttempts', sa.INTEGER(), nullable=True),
    sa.Column('ftPercent', sa.FLOAT(), nullable=True),
    sa.Column('offensiveRb', sa.INTEGER(), nullable=True),
    sa.Column('defensiveRb', sa.INTEGER(), nullable=True),
    sa.Column('totalRb', sa.INTEGER(), nullable=True),
    sa.Column('assists', sa.INTEGER(), nullable=True),
    sa.Column('steals', sa.INTEGER(), nullable=True),
    sa.Column('blocks', sa.INTEGER(), nullable=True),
    sa.Column('turnovers', sa.INTEGER(), nullable=True),
    sa.Column('personalFouls', sa.INTEGER(), nullable=True),
    sa.Column('points', sa.INTEGER(), nullable=True),
    sa.Column('team', sa.VARCHAR(), nullable=True),
    sa.Column('season', sa.INTEGER(), nullable=True),
    sa.Column('playerId', sa.VARCHAR(), nullable=True),
    sa.Column('ATR', sa.FLOAT(), nullable=True),
    sa.Column('PPG', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id_table')
    )
    # ### end Alembic commands ###
